services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    volumes:
      - ./memgraph/lib:/var/lib/memgraph:z
      - ./memgraph/log:/var/log/memgraph:z
      - ./memgraph/etc:/var/etc/memgraph:z
    user: root
    ports:
      - 7687:7687
      - 7444:7444
    command: ["--log-level=TRACE"]
  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - 3000:3000
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687